#ifndef _MIB_H
#define _MIB_H
#include<stdio.h>
typedef struct 
{
    int id;
    char * name;
    char * oid;
}AlarmUnion;


#define MIB_ALARM_EXT_ALM 1
#define MIB_ALARM_DOOR_OPEN 2
#define MIB_ALARM_UL_PA1_OVER_TEMP 3
#define MIB_ALARM_DL_PA1_OVER_TEMP 4
#define MIB_ALARM_UL_PA1_OVER_POWER 5
#define MIB_ALARM_DL_PA1_OVER_POWER 6
#define MIB_ALARM_UL_PA1_VSWR 7
#define MIB_ALARM_DL_PA1_VSWR 8
#define MIB_ALARM_UL_PA1_FAULT 9
#define MIB_ALARM_DL_PA1_FAULT 10
#define MIB_ALARM_OPTIC2_RX_FAULT 11
#define MIB_ALARM_OPTIC2_TX_FAULT 12
#define MIB_ALARM_AC_POWER_OFF 13
#define MIB_ALARM_UL_PA2_OVER_TEMP 14
#define MIB_ALARM_DL_PA2_OVER_TEMP 15
#define MIB_ALARM_UL_PA2_OVER_POWER 16
#define MIB_ALARM_DL_PA2_OVER_POWER 17
#define MIB_ALARM_UL_PA2_VSWR 18
#define MIB_ALARM_DL_PA2_VSWR 19
#define MIB_ALARM_UL_PA2_FAULT 20
#define MIB_ALARM_DL_PA2_FAULT 21
#define MIB_ALARM_BATTERIES_OVER_TEMP 22
#define MIB_ALARM_BATTERIES_OVER_LOW_VOltage 23
#define MIB_ALARM_DC_POWER_OFF 24
#define MIB_ALARM_BATTERIES_DOOR_OPEN 25
#define MIB_ALARM_BATTERIES_LINK 26
#define MIB_ALARM_UL_CH1_UNLOCK 27
#define MIB_ALARM_UL_CH2_UNLOCK 28
#define MIB_ALARM_UL_CH3_UNLOCK 29
#define MIB_ALARM_UL_CH4_UNLOCK 30
#define MIB_ALARM_UL_CH5_UNLOCK 31
#define MIB_ALARM_UL_CH6_UNLOCK 32
#define MIB_ALARM_UL_CH7_UNLOCK 33
#define MIB_ALARM_UL_CH8_UNLOCK 34
#define MIB_ALARM_OPTIC1_RX_FAULT 35
#define MIB_ALARM_DL_CH1_UNLOCK 36
#define MIB_ALARM_DL_CH2_UNLOCK 37
#define MIB_ALARM_DL_CH3_UNLOCK 38
#define MIB_ALARM_DL_CH4_UNLOCK 39
#define MIB_ALARM_DL_CH5_UNLOCK 40
#define MIB_ALARM_DL_CH6_UNLOCK 41
#define MIB_ALARM_DL_CH7_UNLOCK 42
#define MIB_ALARM_DL_CH8_UNLOCK 43
#define MIB_ALARM_ULLINKFAULT 44
#define MIB_ALARM_ODU_OVER_TEMP 45
#define MIB_ALARM_OPTIC1_TX_FAULT 46
#define MIB_ALARM_ODU_DL_UNLINK 47
#define MIB_ALARM_ODU_UL_UNLINK 48
#define MIB_ALARM_ODU_DL_VSWR 49
#define MIB_ALARM_ODU_LO_UNLINK 50
#define MIB_ALARM_CLOCK_UNLOCK 51
#define MIB_ALARM_INPUT_OVER_POWER 52
#define MIB_ALARM_VCO1_UNLOCK 53
#define MIB_ALARM_VCO2_UNLOCK 54
#define MIB_ALARM_FAN1 55
#define MIB_ALARM_FAN2 56
#define MIB_ALARM_UL_LNA_FAULT 57
#define MIB_ALARM_FAN3 58
#define MIB_ALARM_FAN4 59
#define MIB_ALARM_EXT_ALM_2 60
#define MIB_ALARM_EXT_ALM_3 61
#define MIB_ALARM_EXT_ALM_4 62
#define MIB_ALARM_EXT_ALM_5 63
#define MIB_ALARM_EXT_ALM_6 64
#define MIB_ALARM_RTD_SIGNAL 65
#define MIB_ALARM_OFFLINE 66
#define MIB_ALARM_DL_LNA_FAULT 67
#define MIB_ALARM_WEEK_RSSI 68
#define MIB_ALARM_UL_SELF_OSCILLATION 69
#define MIB_ALARM_DL_SELF_OSCILLATION 70
#define MIB_ALARM_OVER_TEMP 71
#define MIB_ALARM_ISOLATION 72
#define MIB_ALARM_SELF_OSCILLATION 73
int get_alarmtype_size();

#endif
